# Generated by Django 5.2 on 2025-04-10 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='format',
            field=models.CharField(choices=[('teamvsteam', 'Team vs Team'), ('individualvindividual', 'Individual vs Individual'), ('team_multi', 'Multiple Teams'), ('individual_multi', 'Multiple Individuals')], default='teamvsteam', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='individuals',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(blank=True, to='participants.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_matches', to='participants.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_matches', to='participants.team'),
        ),
    ]
