# Generated by Django 5.2 on 2025-04-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_team_captain_leaderboard_leaderboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
